### ISSUE TITLE
Create a Jupyter notebook

### ISSUE THREAD

**Issue by namitasshah** [nicole-brewer/jupyterlab-ide#16]
# Task List
- [x] clone repo
- [x] activate a conda environment found in `binder/environment.yml`
- [x] create the notebook
- [x] git add notebook to stage the file
- [x] git commit with a message that contains a closing keyword, for example `commit -m "resolves #16"`
- [x] Push the code to GitHub

**Comment by namitasshah** [comment]
Resolved!
